{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kunmc.lab",
    "module": "ForgeCLI",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeCLI-1.0.1.jar",
          "url": "ForgeCLI-1.0.1.jar",
          "size": 6412,
          "sha512": "b08ba8a97962e23da1957e657084785a30ae3009cf00cea4fea202814cc434537ffc7babd5964ea66522c6ada29a211b8148ee68b22553adb9a5d671c935ff8a",
          "sha256": "f37cfd00c4c0ad09ff3086ca8b83e52a87ea41bd15d49a75392df99cb28a1d41",
          "sha1": "5a141763029d82773736bdfeb61a2347308ce769",
          "md5": "d3dd775287e760a3c8277584a745939c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ForgeCLI",
          "module": "legacy",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "ForgeCLI-1.0.1.jar",
          "url": "ForgeCLI-1.0.1.jar",
          "size": 6412,
          "sha512": "b08ba8a97962e23da1957e657084785a30ae3009cf00cea4fea202814cc434537ffc7babd5964ea66522c6ada29a211b8148ee68b22553adb9a5d671c935ff8a",
          "sha256": "f37cfd00c4c0ad09ff3086ca8b83e52a87ea41bd15d49a75392df99cb28a1d41",
          "sha1": "5a141763029d82773736bdfeb61a2347308ce769",
          "md5": "d3dd775287e760a3c8277584a745939c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeCLI-1.0.1-sources.jar",
          "url": "ForgeCLI-1.0.1-sources.jar",
          "size": 3472,
          "sha512": "688e803d0e46b7620645207832bab229c4d1a6314220d4fb88ec817f30f81657b5329a472986afb5c7dcad1d2770c21036f737223fb57596c857e681c95f4142",
          "sha256": "c99fb3bf144ebfd86d454b2fed6daea889859f528fb2a0d468c51612da4b5c33",
          "sha1": "4ad762a631f52339cbb44042cd81b7cdf97353c4",
          "md5": "f1bf8a906a4440c643c665bd879ac855"
        }
      ]
    }
  ]
}
