{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kunmc.lab",
    "module": "ForgeCLI",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeCLI-1.0.0.jar",
          "url": "ForgeCLI-1.0.0.jar",
          "size": 7522,
          "sha512": "5dfe388fea1d6d7f6753c6ade3de81932de50e32bf25a0231a2642f401232cfee3d188d65d6da3da3408cc083efeb114beb18e3339690fe77020e9b12cf9d298",
          "sha256": "daf50df8897ffcff6780777711ed1aff1510ff258604db7f9221a5329613ade3",
          "sha1": "310d91c4aefac4c6ca9ab20fd189678732734454",
          "md5": "5a99581e5dc1e42a8785e45f4b0c6af7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ForgeCLI",
          "module": "legacy",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "ForgeCLI-1.0.0.jar",
          "url": "ForgeCLI-1.0.0.jar",
          "size": 7522,
          "sha512": "5dfe388fea1d6d7f6753c6ade3de81932de50e32bf25a0231a2642f401232cfee3d188d65d6da3da3408cc083efeb114beb18e3339690fe77020e9b12cf9d298",
          "sha256": "daf50df8897ffcff6780777711ed1aff1510ff258604db7f9221a5329613ade3",
          "sha1": "310d91c4aefac4c6ca9ab20fd189678732734454",
          "md5": "5a99581e5dc1e42a8785e45f4b0c6af7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeCLI-1.0.0-sources.jar",
          "url": "ForgeCLI-1.0.0-sources.jar",
          "size": 3883,
          "sha512": "d6eb3dd8bc848b47ae2dee21bee0bc356ee317c187ce732a81b3e12176840b94d805979909304f02f81851bf3b08665fd570630a4f1c3d48cfb914ed53601e75",
          "sha256": "c8b237ec0108f2507e40a18060ee67f9960803f799ae17aef931faa7d97fd8af",
          "sha1": "8ebd37bc67084e97046d307ff9c8bc5a2be000f8",
          "md5": "8cdfe41aea2b310a0c22a56b1af5df63"
        }
      ]
    }
  ]
}
